#include "runtime.hpp"
#include <cmath>
#include <stdexcept>
Config default_config(uint n,uint m){Config c{};c.count=n;c.opCount=m;c.depth=4;c.dt=0.01f;c.yup=0.0005f;c.epsilon=0.125f;c.mutation=1;c.jitter=1;c.feedback=1;c.phaseRate=.125f;c.radialRate=.01f;c.historyWeight=.75f;c.fieldScale=.005f;return c;}
void validate_config(const Config& c){if(!c.count||c.opCount<31||c.depth>30||((uint64_t(1)<<(c.depth+1))-1)>c.opCount)throw std::runtime_error("Invalid count/operator count/tree depth");if(!(c.dt>0)||!std::isfinite(c.dt)||!std::isfinite(c.yup)||!std::isfinite(c.epsilon)||!std::isfinite(c.mutation)||!std::isfinite(c.phaseRate)||!std::isfinite(c.radialRate)||!std::isfinite(c.historyWeight)||!std::isfinite(c.fieldScale)||c.historyWeight<0||c.historyWeight>1||c.jitter>1||c.feedback>1)throw std::runtime_error("Invalid numerical profile: finite values, positive dt, history weight in [0,1], and one-bit controls required");}
State initialize_state(Config c,uint i){State a{};float r=std::sqrt((float(i)+.5f)/float(c.count)),t=float(i)*2.39996322972865332f;a.u=.5f+.45f*r*std::cos(t);a.v=.5f+.45f*r*std::sin(t);a.rho=std::log(.2f+.4f*r);a.theta=std::fmod(t,DW_TAU);a.ai=2;a.bi=1;a.energy=5;a.rng=dw_rng(756u^(i*747796405u+2891336453u));if(!a.rng)a.rng=756;a.inv00=a.inv11=1;a.alpha_ref=i;a.previousTheta=a.previousPreviousTheta=a.theta;dw_embedding(a);return a;}
Snapshot initialize(Config c,bool includeStates){validate_config(c);Snapshot s;s.cfg=c;if(includeStates)s.states.resize(c.count);s.ops.resize(c.opCount);
 for(uint i=0;i<s.states.size();++i)s.states[i]=initialize_state(c,i);
 for(uint i=0;i<c.opCount;++i){Operator o{};float t=float(i)*2.39996322972865332f,pr=std::sqrt((float(i)+.5f)/float(c.opCount));o.u=.5f+.4f*pr*std::cos(t);o.v=.5f+.4f*pr*std::sin(t);o.radius=.18f+.005f*float(i%5);o.height=.25f;o.phase=.02f*float(i);o.gain=.1f;o.coupling=.9f;o.shear=.1f*std::sin(t);o.du=.03f*std::cos(t);o.dv=.03f*std::sin(t);o.mutationRate=.0002f;o.program=0x341u;o.seed=dw_rng(756u+i*17u);if(!o.seed)o.seed=1;o.kind=i;s.ops[i]=o;}return s;}
void cpu_step(Snapshot& s){if(s.cfg.epoch==UINT32_MAX)throw std::runtime_error("The uint32 epoch ABI is exhausted");auto old=s.ops;auto next=s.states;const Config c=s.cfg;
 for(uint i=0;i<c.opCount;++i){uint a=dw_feedback_index(i,17u,c.epoch,0u,c.count),b=dw_feedback_index(i,31u,c.epoch,1u,c.count);s.ops[i]=dw_mutate(old[i],old[30],old[5],s.states[a],s.states[b],c);}
 for(uint i=0;i<c.count;++i)next[i]=dw_evolve(s.states[i],c,i,s.ops.data());s.states.swap(next);++s.cfg.epoch;}
