#include "runtime.hpp"
#include "spirv.hpp"
#include <vulkan/vulkan.h>
#include <algorithm>
#include <chrono>
#include <cstring>
#include <cstdlib>
#include <sstream>
#include <stdexcept>
#include <cctype>
namespace {
void check(VkResult r,const char* where){if(r!=VK_SUCCESS)throw std::runtime_error(std::string(where)+" (VkResult "+std::to_string(int(r))+")");}
std::string lower(std::string x){for(char& c:x)c=char(std::tolower(static_cast<unsigned char>(c)));return x;}
struct Buffer {VkBuffer handle=VK_NULL_HANDLE;VkDeviceMemory memory=VK_NULL_HANDLE;VkDeviceSize size=0,allocated=0;bool coherent=false;};
}
struct VulkanRuntime::Impl {
 VkInstance instance=VK_NULL_HANDLE;VkPhysicalDevice physical=VK_NULL_HANDLE;VkDevice device=VK_NULL_HANDLE;VkQueue queue=VK_NULL_HANDLE;
 VkPhysicalDeviceProperties props{};VkPhysicalDeviceMemoryProperties memory{};VkPhysicalDeviceMemoryBudgetPropertiesEXT budget{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_BUDGET_PROPERTIES_EXT};
 VkCommandPool commandPool=VK_NULL_HANDLE;VkCommandBuffer command=VK_NULL_HANDLE;VkFence fence=VK_NULL_HANDLE;
 VkDescriptorSetLayout descriptorLayout=VK_NULL_HANDLE;VkDescriptorPool descriptorPool=VK_NULL_HANDLE;VkDescriptorSet sets[2]{};
 VkPipelineLayout pipelineLayout=VK_NULL_HANDLE;VkPipeline mutatePipeline=VK_NULL_HANDLE,evolvePipeline=VK_NULL_HANDLE;VkQueryPool queries=VK_NULL_HANDLE;
 Buffer states[2],operators[2],staging;Config cfg{};uint parity=0,queueFamily=0,timestampBits=0;
 bool budgetAvailable=false,validationEnabled=false;double seconds=0,wallSeconds=0;uint64_t uploadBytes=0,downloadBytes=0,totalEpochs=0;
 ~Impl(){if(device){vkDeviceWaitIdle(device);if(queries)vkDestroyQueryPool(device,queries,nullptr);if(mutatePipeline)vkDestroyPipeline(device,mutatePipeline,nullptr);if(evolvePipeline)vkDestroyPipeline(device,evolvePipeline,nullptr);if(descriptorPool)vkDestroyDescriptorPool(device,descriptorPool,nullptr);if(pipelineLayout)vkDestroyPipelineLayout(device,pipelineLayout,nullptr);if(descriptorLayout)vkDestroyDescriptorSetLayout(device,descriptorLayout,nullptr);if(fence)vkDestroyFence(device,fence,nullptr);if(commandPool)vkDestroyCommandPool(device,commandPool,nullptr);for(auto& b:states)destroy(b);for(auto& b:operators)destroy(b);destroy(staging);vkDestroyDevice(device,nullptr);}if(instance)vkDestroyInstance(instance,nullptr);}
 void destroy(Buffer& b){if(b.handle)vkDestroyBuffer(device,b.handle,nullptr);if(b.memory)vkFreeMemory(device,b.memory,nullptr);b={};}
 void make_buffer(Buffer& b,VkDeviceSize size,VkBufferUsageFlags usage,VkMemoryPropertyFlags required){
  b.size=size;VkBufferCreateInfo ci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};ci.size=size;ci.usage=usage;ci.sharingMode=VK_SHARING_MODE_EXCLUSIVE;check(vkCreateBuffer(device,&ci,nullptr,&b.handle),"vkCreateBuffer");
  VkMemoryRequirements req{};vkGetBufferMemoryRequirements(device,b.handle,&req);uint type=UINT32_MAX;int score=-1;
  for(uint i=0;i<memory.memoryTypeCount;++i){auto flags=memory.memoryTypes[i].propertyFlags;if((req.memoryTypeBits&(1u<<i))&&(flags&required)==required){int candidate=((flags&VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)!=0);if(candidate>score){type=i;score=candidate;}}}
  if(type==UINT32_MAX)throw std::runtime_error("No suitable Vulkan memory type");
  VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=type;check(vkAllocateMemory(device,&ai,nullptr,&b.memory),"vkAllocateMemory");b.allocated=req.size;b.coherent=(memory.memoryTypes[type].propertyFlags&VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)!=0;check(vkBindBufferMemory(device,b.handle,b.memory,0),"vkBindBufferMemory");
 }
 void begin(){check(vkResetCommandBuffer(command,0),"vkResetCommandBuffer");VkCommandBufferBeginInfo info{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};info.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;check(vkBeginCommandBuffer(command,&info),"vkBeginCommandBuffer");}
 void finish(){check(vkEndCommandBuffer(command),"vkEndCommandBuffer");check(vkResetFences(device,1,&fence),"vkResetFences");VkSubmitInfo s{VK_STRUCTURE_TYPE_SUBMIT_INFO};s.commandBufferCount=1;s.pCommandBuffers=&command;check(vkQueueSubmit(queue,1,&s,fence),"vkQueueSubmit");check(vkWaitForFences(device,1,&fence,VK_TRUE,UINT64_MAX),"vkWaitForFences");}
 void barrier(VkPipelineStageFlags from,VkPipelineStageFlags to,VkAccessFlags src,VkAccessFlags dst){VkMemoryBarrier b{VK_STRUCTURE_TYPE_MEMORY_BARRIER};b.srcAccessMask=src;b.dstAccessMask=dst;vkCmdPipelineBarrier(command,from,to,0,1,&b,0,nullptr,0,nullptr);}
 void upload(Buffer& target,const void* data,size_t bytes){void* map=nullptr;check(vkMapMemory(device,staging.memory,0,VK_WHOLE_SIZE,0,&map),"vkMapMemory upload");std::memcpy(map,data,bytes);if(!staging.coherent){VkMappedMemoryRange r{VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE};r.memory=staging.memory;r.size=VK_WHOLE_SIZE;check(vkFlushMappedMemoryRanges(device,1,&r),"vkFlushMappedMemoryRanges");}vkUnmapMemory(device,staging.memory);begin();VkBufferCopy copy{0,0,bytes};vkCmdCopyBuffer(command,staging.handle,target.handle,1,&copy);barrier(VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_TRANSFER_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT);finish();uploadBytes+=bytes;}
 void read(Buffer& source,void* data,size_t bytes){begin();barrier(VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_TRANSFER_READ_BIT);VkBufferCopy copy{0,0,bytes};vkCmdCopyBuffer(command,source.handle,staging.handle,1,&copy);barrier(VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_HOST_BIT,VK_ACCESS_TRANSFER_WRITE_BIT,VK_ACCESS_HOST_READ_BIT);finish();void* map=nullptr;check(vkMapMemory(device,staging.memory,0,VK_WHOLE_SIZE,0,&map),"vkMapMemory read");if(!staging.coherent){VkMappedMemoryRange r{VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE};r.memory=staging.memory;r.size=VK_WHOLE_SIZE;check(vkInvalidateMappedMemoryRanges(device,1,&r),"vkInvalidateMappedMemoryRanges");}std::memcpy(data,map,bytes);vkUnmapMemory(device,staging.memory);downloadBytes+=bytes;}
 VkPipeline pipeline(const uint32_t* words,size_t bytes){VkShaderModule module=VK_NULL_HANDLE;VkShaderModuleCreateInfo mi{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};mi.codeSize=bytes;mi.pCode=words;check(vkCreateShaderModule(device,&mi,nullptr,&module),"vkCreateShaderModule");VkComputePipelineCreateInfo pi{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};pi.layout=pipelineLayout;pi.stage.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;pi.stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;pi.stage.module=module;pi.stage.pName="main";VkPipeline result=VK_NULL_HANDLE;auto status=vkCreateComputePipelines(device,VK_NULL_HANDLE,1,&pi,nullptr,&result);vkDestroyShaderModule(device,module,nullptr);check(status,"vkCreateComputePipelines");return result;}
 void setup(const Snapshot& initial,const std::string& wanted,bool allowSoftware){cfg=initial.cfg;validate_config(cfg);
  VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="Dawnwood Interactive DWI-N1";app.applicationVersion=VK_MAKE_VERSION(0,3,0);app.apiVersion=VK_API_VERSION_1_1;
  VkInstanceCreateInfo ci{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ci.pApplicationInfo=&app;const char* validation="VK_LAYER_KHRONOS_validation";
  if(std::getenv("DAWNWOOD_VALIDATION")){uint n=0;check(vkEnumerateInstanceLayerProperties(&n,nullptr),"enumerate layers");std::vector<VkLayerProperties> layers(n);check(vkEnumerateInstanceLayerProperties(&n,layers.data()),"enumerate layers");for(auto& l:layers)if(std::string(l.layerName)==validation)validationEnabled=true;if(!validationEnabled)throw std::runtime_error("Validation requested but VK_LAYER_KHRONOS_validation is unavailable");ci.enabledLayerCount=1;ci.ppEnabledLayerNames=&validation;}
  check(vkCreateInstance(&ci,nullptr,&instance),"vkCreateInstance Vulkan 1.1");uint n=0;check(vkEnumeratePhysicalDevices(instance,&n,nullptr),"enumerate devices");std::vector<VkPhysicalDevice> devices(n);check(vkEnumeratePhysicalDevices(instance,&n,devices.data()),"enumerate devices");
  std::string available;int best=-1;for(auto d:devices){VkPhysicalDeviceProperties prop;vkGetPhysicalDeviceProperties(d,&prop);available+=std::string(prop.deviceName)+"; ";if(!wanted.empty()&&lower(prop.deviceName).find(lower(wanted))==std::string::npos)continue;if(prop.apiVersion<VK_API_VERSION_1_1)continue;if(prop.deviceType==VK_PHYSICAL_DEVICE_TYPE_CPU&&!allowSoftware)continue;int rank=prop.deviceType==VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU?3:(prop.deviceType==VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU?2:1);if(rank>best){physical=d;props=prop;best=rank;}}
  if(!physical)throw std::runtime_error("No matching Vulkan 1.1 GPU. Available: "+available+". CPU ICDs require --allow-software.");
  uint qn=0;vkGetPhysicalDeviceQueueFamilyProperties(physical,&qn,nullptr);std::vector<VkQueueFamilyProperties> qs(qn);vkGetPhysicalDeviceQueueFamilyProperties(physical,&qn,qs.data());queueFamily=UINT32_MAX;for(uint i=0;i<qn;++i)if(qs[i].queueCount&&(qs[i].queueFlags&VK_QUEUE_COMPUTE_BIT)){queueFamily=i;timestampBits=qs[i].timestampValidBits;if(!(qs[i].queueFlags&VK_QUEUE_GRAPHICS_BIT))break;}
  if(queueFamily==UINT32_MAX)throw std::runtime_error("No compute queue");
  VkDeviceSize sb=VkDeviceSize(cfg.count)*sizeof(State),ob=VkDeviceSize(cfg.opCount)*sizeof(Operator);
  if(sb>props.limits.maxStorageBufferRange||ob>props.limits.maxStorageBufferRange)throw std::runtime_error("Requested buffer exceeds maxStorageBufferRange; reduce count or partition workload");
  if((uint64_t(cfg.count)+63)/64>props.limits.maxComputeWorkGroupCount[0]||(uint64_t(cfg.opCount)+63)/64>props.limits.maxComputeWorkGroupCount[0])throw std::runtime_error("Dispatch exceeds device workgroup limit");
  uint en=0;check(vkEnumerateDeviceExtensionProperties(physical,nullptr,&en,nullptr),"device extensions");std::vector<VkExtensionProperties> exts(en);check(vkEnumerateDeviceExtensionProperties(physical,nullptr,&en,exts.data()),"device extensions");for(auto& e:exts)if(std::string(e.extensionName)==VK_EXT_MEMORY_BUDGET_EXTENSION_NAME)budgetAvailable=true;
  VkPhysicalDeviceMemoryProperties2 mem2{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2};if(budgetAvailable)mem2.pNext=&budget;vkGetPhysicalDeviceMemoryProperties2(physical,&mem2);memory=mem2.memoryProperties;
  VkDeviceSize largest=0;for(uint i=0;i<memory.memoryHeapCount;++i)if(memory.memoryHeaps[i].flags&VK_MEMORY_HEAP_DEVICE_LOCAL_BIT){VkDeviceSize free=memory.memoryHeaps[i].size;if(budgetAvailable)free=budget.heapBudget[i]>budget.heapUsage[i]?budget.heapBudget[i]-budget.heapUsage[i]:0;largest=std::max(largest,free);}
  if(largest&&2*sb+2*ob+std::max(sb,ob)>largest*8/10)throw std::runtime_error("Requested live buffers exceed 80% of the reported largest device-local available heap; reduce count");
  float priority=1;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=queueFamily;qi.queueCount=1;qi.pQueuePriorities=&priority;
  VkDeviceCreateInfo di{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};di.queueCreateInfoCount=1;di.pQueueCreateInfos=&qi;const char* be=VK_EXT_MEMORY_BUDGET_EXTENSION_NAME;if(budgetAvailable){di.enabledExtensionCount=1;di.ppEnabledExtensionNames=&be;}check(vkCreateDevice(physical,&di,nullptr,&device),"vkCreateDevice");vkGetDeviceQueue(device,queueFamily,0,&queue);
  VkCommandPoolCreateInfo cp{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};cp.queueFamilyIndex=queueFamily;cp.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;check(vkCreateCommandPool(device,&cp,nullptr,&commandPool),"vkCreateCommandPool");VkCommandBufferAllocateInfo ca{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ca.commandPool=commandPool;ca.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ca.commandBufferCount=1;check(vkAllocateCommandBuffers(device,&ca,&command),"vkAllocateCommandBuffers");VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};check(vkCreateFence(device,&fi,nullptr,&fence),"vkCreateFence");
  for(auto& b:states)make_buffer(b,sb,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  for(auto& b:operators)make_buffer(b,ob,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
  make_buffer(staging,std::max(sb,ob),VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
  VkDescriptorSetLayoutBinding bindings[4]{};for(uint i=0;i<4;++i){bindings[i].binding=i;bindings[i].descriptorCount=1;bindings[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;bindings[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}
  VkDescriptorSetLayoutCreateInfo li{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};li.bindingCount=4;li.pBindings=bindings;check(vkCreateDescriptorSetLayout(device,&li,nullptr,&descriptorLayout),"vkCreateDescriptorSetLayout");
  VkPushConstantRange push{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(Config)};VkPipelineLayoutCreateInfo pli{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pli.setLayoutCount=1;pli.pSetLayouts=&descriptorLayout;pli.pushConstantRangeCount=1;pli.pPushConstantRanges=&push;check(vkCreatePipelineLayout(device,&pli,nullptr,&pipelineLayout),"vkCreatePipelineLayout");
  VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,8};VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=2;dpi.poolSizeCount=1;dpi.pPoolSizes=&ps;check(vkCreateDescriptorPool(device,&dpi,nullptr,&descriptorPool),"vkCreateDescriptorPool");VkDescriptorSetLayout layouts[2]={descriptorLayout,descriptorLayout};VkDescriptorSetAllocateInfo da{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};da.descriptorPool=descriptorPool;da.descriptorSetCount=2;da.pSetLayouts=layouts;check(vkAllocateDescriptorSets(device,&da,sets),"vkAllocateDescriptorSets");
  for(uint p=0;p<2;++p){VkDescriptorBufferInfo bi[4]={{states[p].handle,0,sb},{states[1-p].handle,0,sb},{operators[p].handle,0,ob},{operators[1-p].handle,0,ob}};VkWriteDescriptorSet writes[4]{};for(uint i=0;i<4;++i){writes[i].sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;writes[i].dstSet=sets[p];writes[i].dstBinding=i;writes[i].descriptorCount=1;writes[i].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;writes[i].pBufferInfo=&bi[i];}vkUpdateDescriptorSets(device,4,writes,0,nullptr);}
  mutatePipeline=pipeline(mutate_spv,sizeof(mutate_spv));evolvePipeline=pipeline(evolve_spv,sizeof(evolve_spv));
  if(timestampBits){VkQueryPoolCreateInfo qp{VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO};qp.queryType=VK_QUERY_TYPE_TIMESTAMP;qp.queryCount=2;check(vkCreateQueryPool(device,&qp,nullptr,&queries),"vkCreateQueryPool");}
  upload(states[0],initial.states.data(),size_t(sb));upload(operators[0],initial.ops.data(),size_t(ob));
 }
 void advance(uint steps){if(!steps){seconds=wallSeconds=0;return;}if(uint64_t(cfg.epoch)+steps>UINT32_MAX)throw std::runtime_error("This binary's epoch ABI is uint32; checkpoint before changing the epoch representation");auto start=std::chrono::steady_clock::now();begin();if(queries){vkCmdResetQueryPool(command,queries,0,2);vkCmdWriteTimestamp(command,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,queries,0);}
  for(uint k=0;k<steps;++k){vkCmdBindDescriptorSets(command,VK_PIPELINE_BIND_POINT_COMPUTE,pipelineLayout,0,1,&sets[parity],0,nullptr);vkCmdPushConstants(command,pipelineLayout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(Config),&cfg);vkCmdBindPipeline(command,VK_PIPELINE_BIND_POINT_COMPUTE,mutatePipeline);vkCmdDispatch(command,(cfg.opCount+63u)/64u,1,1);barrier(VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT);vkCmdBindPipeline(command,VK_PIPELINE_BIND_POINT_COMPUTE,evolvePipeline);vkCmdDispatch(command,(cfg.count+63u)/64u,1,1);barrier(VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT);parity=1u-parity;++cfg.epoch;}
  if(queries)vkCmdWriteTimestamp(command,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,queries,1);finish();wallSeconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();seconds=wallSeconds;if(queries){uint64_t times[2]{};check(vkGetQueryPoolResults(device,queries,0,2,sizeof(times),times,sizeof(uint64_t),VK_QUERY_RESULT_64_BIT|VK_QUERY_RESULT_WAIT_BIT),"vkGetQueryPoolResults");uint64_t delta=times[1]-times[0];if(timestampBits<64)delta&=(uint64_t(1)<<timestampBits)-1;seconds=double(delta)*double(props.limits.timestampPeriod)*1e-9;}totalEpochs+=steps;
 }
};
VulkanRuntime::VulkanRuntime(const Snapshot& s,const std::string& name,bool allowSoftware):p(new Impl){p->setup(s,name,allowSoftware);}
VulkanRuntime::~VulkanRuntime()=default;
void VulkanRuntime::advance(uint steps){p->advance(steps);}
Snapshot VulkanRuntime::download(){Snapshot s;s.cfg=p->cfg;s.states.resize(s.cfg.count);s.ops.resize(s.cfg.opCount);p->read(p->states[p->parity],s.states.data(),s.states.size()*sizeof(State));p->read(p->operators[p->parity],s.ops.data(),s.ops.size()*sizeof(Operator));return s;}
double VulkanRuntime::last_seconds()const{return p->seconds;}
bool VulkanRuntime::software()const{return p->props.deviceType==VK_PHYSICAL_DEVICE_TYPE_CPU;}
std::string VulkanRuntime::device_json()const{VkPhysicalDeviceFeatures features{};vkGetPhysicalDeviceFeatures(p->physical,&features);VkFormatProperties bc5{},eac{},astc{};vkGetPhysicalDeviceFormatProperties(p->physical,VK_FORMAT_BC5_UNORM_BLOCK,&bc5);vkGetPhysicalDeviceFormatProperties(p->physical,VK_FORMAT_EAC_R11G11_UNORM_BLOCK,&eac);vkGetPhysicalDeviceFormatProperties(p->physical,VK_FORMAT_ASTC_4x4_UNORM_BLOCK,&astc);std::ostringstream o;uint64_t allocated=p->staging.allocated;for(auto& b:p->states)allocated+=b.allocated;for(auto& b:p->operators)allocated+=b.allocated;
 o<<"{\"name\":"<<json_escape(p->props.deviceName)<<",\"vendor_id\":"<<p->props.vendorID<<",\"device_id\":"<<p->props.deviceID<<",\"api_version\":"<<p->props.apiVersion<<",\"driver_version\":"<<p->props.driverVersion<<",\"software_device\":"<<(software()?"true":"false")<<",\"validation_layer_enabled\":"<<(p->validationEnabled?"true":"false")<<",\"memory_budget_extension\":"<<(p->budgetAvailable?"true":"false")<<",\"texture_compression_BC\":"<<(features.textureCompressionBC?"true":"false")<<",\"BC5_sampled_image\":"<<((bc5.optimalTilingFeatures&VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT)?"true":"false")<<",\"EAC_RG11_sampled_image\":"<<((eac.optimalTilingFeatures&VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT)?"true":"false")<<",\"ASTC_4x4_sampled_image\":"<<((astc.optimalTilingFeatures&VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT)?"true":"false")<<",\"max_compute_shared_memory_bytes\":"<<p->props.limits.maxComputeSharedMemorySize<<",\"max_storage_buffer_range\":"<<p->props.limits.maxStorageBufferRange<<",\"allocated_buffer_bytes\":"<<allocated<<",\"upload_bytes\":"<<p->uploadBytes<<",\"download_bytes\":"<<p->downloadBytes<<",\"completed_epochs\":"<<p->totalEpochs<<",\"advance_buffer_copy_commands\":0,\"timer\":"<<json_escape(p->queries?"Vulkan device timestamps":"host fence wall time")<<",\"last_dispatch_seconds\":"<<p->seconds<<",\"last_wall_seconds\":"<<p->wallSeconds<<",\"heaps\":[";
 for(uint i=0;i<p->memory.memoryHeapCount;++i){if(i)o<<",";o<<"{\"index\":"<<i<<",\"size\":"<<p->memory.memoryHeaps[i].size<<",\"device_local\":"<<((p->memory.memoryHeaps[i].flags&VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)?"true":"false");if(p->budgetAvailable)o<<",\"budget_at_start\":"<<p->budget.heapBudget[i]<<",\"usage_at_start\":"<<p->budget.heapUsage[i];o<<"}";}o<<"]}";return o.str();}
